// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfuwenylojhabresnrvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmdXdlbnlsb2poYWJyZXNucnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMTQ3NzEsImV4cCI6MjA4ODU5MDc3MX0._1kAuL6VJYuWJvqWmu9EuQqHwCW5OL_AxyMdXXz-lps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});